softwarebyze/Places

- .gitignore
- firebaseConfig.js
- metro.config.js
- package-lock.json
- package.json
> adds firebase starting point

- metro.config.js
fixes the last PR that had typo in metro.config
> accidently had declaration twice in metro.config

- components/Start/Index.js
- components/Start/pages/JoinPlacePage.js
- components/Start/pages/NavigatorPage.js
- settings/Terms.js
worked further on tab, yet to create screens for neighbor, maps, profile
> 47-navigate-back-to-home-screen-from-pressing-back-button-on-join-a-place-screen

- App.js
- components/Start/elements/Continues.js
- components/Start/pages/HomePage.js
- components/Start/pages/InterestsPage.js
- components/Start/pages/ProfilePage.js
- components/Start/styles/Styles.js
- package-lock.json
- package.json
- settings/Colors.js
> 55-create-the-dropdowns-on-the-home-screen

- components/Start/pages/HomePage.js
- components/Start/styles/Styles.js
Fixed issue by adding double quotes in the fontWeight values. Ref: https://stackoverflow.com/questions/58771086/error-while-updating-property-fontsize-in-shadow-node-of-type-rcttext
> 64-problem-with-fonts-on-android

- components/Start/pages/InterestsPage.js
- components/Start/pages/StartPage.js
- components/Start/styles/Styles.js
choosing interests is looking great
> 58-frontend-for-selecting-minimum-5-interests

- components/Start/pages/HomePage.js
- components/Start/pages/LocationPage.js
- components/Start/styles/Styles.js
the basic choose location dropdown is looking good
> 61-frontend-for-choose-a-location-just-the-grey-text-and-a-dropdown

- components/Start/styles/Styles.js
for some reason styles didnt get saved. this pr fixes them
> Join-a-place-category-styles

- components/Start/pages/StartPage.js
> Login-navigation

- components/Start/elements/Details.js
- package-lock.json
- package.json
Reverts softwarebyze/Places#81
> Revert "59 finish sign up frontend"

- components/Start/elements/Details.js
fixed problem with shrunken inputs (android)
> 107-displaced-titles-and-inputs

- components/Start/pages/MapsPage.js
- package-lock.json
- package.json
> 109-add-a-map

- components/Start/styles/Styles.js
Increased fontsize of email and password requirement text.
> 125-increase-font-size-of-sign-uplog-in-feedback-messages

- eas.json
Added an ios simulator build profile. You might be able to build it by following this: https://docs.expo.dev/build-reference/simulators/
> added a profile for an ios development build and it worked

- components/Start/elements/SheetBody.js
- components/Start/elements/SheetHeader.js
- components/Start/pages/CategoryPage.js
- components/Start/styles/Styles.js
> new sheet header

- components/pages/SignUpPage.js
removed the double navigator.replace('Details') in handleSignUp()
> Fix-double-details-nav

- components/pages/MapsPage.js
- package-lock.json
- package.json
fetching events from firebase is working nicely
> 161-load-events-from-firebase

- components/pages/MapsPage.js
event details is in a bottom sheet and the plus button brings up a sheet for create event
> 165-plus-button-brings-up-sheet

- app.json
- components/pages/MapsPage.js
google maps sdk should be all set up! just need to rebuild. can do that after we merge
> 170-maps-sdk-setup

- components/pages/MapsPage.js
- package-lock.json
- package.json
> 137-location-input-with-google-maps-autocomplete

- App.js
- components/pages/CategoryPage.js
- components/pages/ChannelInfoPage.js
created page and function to add place channel to user's list
> 175-channel-info-page

- components/pages/ChannelInfoPage.js
when clicking to join a place, screen will navigate to that chatroom
> 191-after-you-click-join-to-join-a-place-navigate-to-that-places-chat-screen

- components/elements/AddCityForm.js
- components/pages/HomePage.js
- firebase/users.js
moved functions to designated folder
> 90-query-for-cities

- components/elements/Details.js
https://github.com/softwarebyze/Places/assets/77241170/7818bff4-fdcb-4d25-ac08-5a02cd72f5be
> added spinner to details page

- components/pages/LocationPage.js
- components/pages/LoginPage.js
- firebaseConfig.js
I think the fix was to set the cloud functions location correctly (based on the extension, not the project)
No more need for slow onrender!
**Please test before approving**
https://github.com/softwarebyze/Places/assets/77241170/12b9b28e-8397-4507-bbe2-cd82d1c1c27a
> switched from onrender to firebase extension

- components/pages/InterestsPage.js
- components/styles/Styles.js
> Added text on InterestsPage explaining to pick 5 interests

- components/elements/Details.tsx
- components/helper/convertTimestampToDateAndTime.ts
- components/pages/LocationPage.tsx
- components/pages/LoginPage.tsx
- components/pages/MapsPage.tsx
- firebase/events.ts
- firebase/users.ts
most of it has been moved. im ok with merging at this point
> 238 put all firebase stuff in the same place

- components/pages/HomePage.tsx
Im not seeing any typescript warnings about navigation :) ready to merge
> 241 fix typescript issues with navigation

- App.tsx
- components/navigation/HomeStack.tsx
- components/navigation/types.ts
- components/pages/CategoryPage.tsx
- components/pages/ChannelInfoPage.tsx
- components/pages/HomePage.tsx
- components/pages/JoinPlacePage.tsx
- settings/Terms.ts
Closes #253 
https://github.com/softwarebyze/Places/assets/77241170/3c2b3b48-ce99-4abc-9b7e-81c04ce9da6a
> 253 join a place is broken mvp

- components/pages/HomePage.tsx
https://github.com/softwarebyze/Places/assets/77241170/b852c782-7599-42a2-a6bf-8e070be82d6e
> home screen scrolling working super nice (mvp)

- components/elements/AddCityForm.tsx
- components/elements/CitiesDropdown.tsx
- components/elements/Details.tsx
- components/elements/_Dropdown.tsx
- components/pages/HomePage.tsx
- components/pages/LoginPage.tsx
- components/pages/SignUpPage.tsx
- components/styles/Styles.ts
- data/cities.ts
- firebase/users.ts
- adding a city is working well
- if you press add a city and you are in all the cities, there is a nice message
- bottom modal closes after u add a city
> 240 after adding city close bottom modal

- components/elements/_Dropdown.tsx
- components/pages/HomePage.tsx
- components/styles/Styles.ts
- package-lock.json
- package.json
- fixes glitchy dropdowns (#261)
- removes react-native-collapsible library
> fixes glitchy home screen dropdowns

- app.json
- eas.json
- ios/Places/Supporting/Expo.plist
> Configured EAS Updates
